blank_issues_enabled: false

contact_links:
  - name: ğŸŒ¸ p5.js Issues
    url: https://github.com/processing/p5.js/issues
    about: Report issues with the p5.js here.
  - name: ğŸŒ Website Issues
    url: https://github.com/processing/p5.js-website/issues
    about: Report issues with the p5.js website here.
  - name: ğŸ’¬ Forum
    url: https://discourse.processing.org/c/p5js
    about: Have other questions about using p5.js? Ask them here!